name: Run pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
        env:
          POETRY_HOME: ${{github.workspace}}/.poetry
          POETRY_VERSION: 1.6.1

      - name: Install project dependencies
        run: |
          cd ${{github.workspace}}
          ${{env.POETRY_HOME}}/bin/poetry install

      - name: Run pytest
        run: |
          cd ${{github.workspace}}
          ${{env.POETRY_HOME}}/bin/poetry run pytest