name: Run pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        env:
          POETRY_HOME: $HOME/.poetry

      - name: Install project dependencies
        run: |
          cd $GITHUB_WORKSPACE
          $POETRY_HOME/bin/poetry install

      - name: Run pytest
        run: |
          cd $GITHUB_WORKSPACE
          $POETRY_HOME/bin/poetry run pytest